name: foreground_service_isolate_example
description: "Demonstrates how to use the foreground_service_isolate plugin."
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^22.3.0
  foreground_service_isolate:
    path: ../
  material_ui: ^1.1.1
  permission_handler: ^13.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  rexios_lints: ^19.0.0

flutter:
  uses-material-design: true
